# Generated by Django 2.0.3 on 2018-03-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_firstname', models.CharField(max_length=200)),
                ('teacher_lastname', models.CharField(max_length=200)),
                ('teacher_subject', models.CharField(max_length=200)),
                ('teacher_age', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
